//
// Created by limo on 12/13/17.
//

#ifndef RAKEMAN_ENGINE_CONFIG_H
#define RAKEMAN_ENGINE_CONFIG_H

#define KEY_TM_DICT "TEMP_DICT_HASH"
#define KEY_HM_DICT "MAIN_DICT_HASH"

#define KEY_MSG_QUEUE "TASK_QUEUE"

#define KEY_RESPONSE_NUM_BREAK_IN_PROCESSING "NUM_BREAK_IN_PROCESS"
#define KEY_RESPONSE_NUM_MERGE_IN_PROCESSING "NUM_MERGE_IN_PROCESS"

#define KEY_RESPONSE_BREAK_FAIL_QUEUE "RESPONSE_BREAK_FAIL_QUEUE"
#define KEY_RESPONSE_MERGE_FAIL_QUEUE "RESPONSE_MERGE_FAIL_QUEUE"

#define KEY_RESPONSE_QUERY_HASH "RESPONSE_QUERY_HASH"

#define NAME_LOG "CONSOLE"

#endif //RAKEMAN_ENGINE_CONFIG_H
